### ISSUE TITLE
浏览器插件自动添加代理前缀

### ISSUE THREAD

**Issue by augenstern326** [gaboolic/vercel-reverse-proxy#10]
感谢作者分享，但在使用时，总是需要添加自己域名前缀，感觉有点麻烦，我在想是否可以写一个浏览器插件，在访问时自动添加前缀，可以设置需要代理的网站和白名单

**Comment by gaboolic** [comment]
> 

我也看了一下浏览器插件的开发文档，发现只有rediret，没有forward
没有一个方便的方式 来篡改调用接口的url
你有什么好的方法吗

**Comment by orangesummertime** [comment]
你可以自己做一个html页面，用点js实现你的需求，不难

**Comment by augenstern326** [comment]
> > 
> 
> 我也看了一下浏览器插件的开发文档，发现只有rediret，没有forward 没有一个方便的方式 来篡改调用接口的url 你有什么好的方法吗

不好意思，我暂时也没有什么好办法，还得研究一下

**Comment by augenstern326** [comment]
> 你可以自己做一个html页面，用点js实现你的需求，不难

你有具体的js例子嘛，如果可行，可以放到插件的background.js里后台执行

**Comment by augenstern326** [comment]
目前找到了一个办法就是用这个来redirect，里面可以配置自己的规则
https://github.com/requestly/requestly
