### ISSUE TITLE
https://自己域名/proxy/api.openai.com/v1/chat/completions

### ISSUE THREAD

**Issue by DragonBoyYYDS** [gaboolic/vercel-reverse-proxy#12]
访问该网址显示下面图片，请问解决方法

**Comment by DragonBoyYYDS** [comment]
![image](https://github.com/gaboolic/vercel-reverse-proxy/assets/90492565/46b8ca79-b181-4405-966e-7f20b2611889)

**Comment by DragonBoyYYDS** [comment]
@gaboolic

**Comment by gaboolic** [comment]
这是openai给你返回的，你看下文档，要把key传过去

**Comment by DragonBoyYYDS** [comment]
请问是看哪个文档，就三个文档吗。怎么传key过去呢？

**Comment by DragonBoyYYDS** [comment]
@gaboolic
