### ISSUE TITLE
502超时

### ISSUE THREAD

**Issue by IILee5** [gaboolic/vercel-reverse-proxy#14]
![image](https://github.com/gaboolic/vercel-reverse-proxy/assets/40862062/b4f40d7f-ac3d-4697-bb66-2683ca67683a)
像这种访问OpenAi时，因为prompt要求，生成文本的时间过长，导致超时的502应该怎么解决呢。

**Comment by gaboolic** [comment]
用流式？

**Comment by gaboolic** [comment]
个人账户无解，最大10秒
官方文档：

Serverless Function Execution Timeout
无服务器函数执行超时

The amount of time (in seconds) that a [Serverless Function](https://vercel.com/docs/concepts/functions/serverless-functions) is allowed to process an HTTP request before it must respond. The maximum execution timeout is 10 seconds when deployed on a Personal Account (Hobby plan). For Teams, the execution timeout is 60 seconds (Pro plan) or 900 seconds (Enterprise plan). [Edge Functions](https://vercel.com/docs/concepts/functions/edge-functions) provide an alternative that do not have a [maximum execution timeout](https://vercel.com/docs/concepts/functions/edge-functions/limitations#maximum-initial-response-time) and that also allow you to continue [streaming responses](https://vercel.com/docs/concepts/functions/edge-functions/streaming).
允许无服务器函数在必须响应之前处理 HTTP 请求的时间量（以秒为单位）。部署在个人帐户（爱好计划）上时，最大执行超时为 10 秒。对于 Teams，执行超时为 60 秒（专业计划）或 900 秒（企业计划）。边缘函数提供了一种替代方案，它没有最大执行超时，还允许您继续流式处理响应。

For more information, see the [Execution Timeout](https://vercel.com/docs/concepts/functions/serverless-functions#execution-timeout) section.
有关详细信息，请参阅执行超时部分。
