### ISSUE TITLE
请问要怎么支持wss转发

### ISSUE THREAD

**Issue by zjw710** [gaboolic/vercel-reverse-proxy#18]
请问要怎么支持wss转发？

**Comment by gaboolic** [comment]
这个不支持，得写代码了。等有空重新写一个ws代理的项目吧

**Comment by zjw710** [comment]
您好，您发给嘉伟的邮件已经收到。。。

**Comment by ilovesusu** [comment]
@gaboolic 要是没空,大概说说怎么实现吧,我想实现一个,但是没思路啊

**Comment by gaboolic** [comment]
> @gaboolic 要是没空,大概说说怎么实现吧,我想实现一个,但是没思路啊

vercel经过研究 不支持ws
我发现我的另一个项目可以https://github.com/gaboolic/cloudflare-reverse-proxy
