### ISSUE TITLE
请求openai返回的错误，求解决方法？

### ISSUE THREAD

**Issue by DragonBoyYYDS** [gaboolic/vercel-reverse-proxy#19]
就和例子那样，改了api_base，然后对话返回这个是什么意思？
msg: {  "error": {    "message": "Unrecognized request argument supplied: messages"
msg: "type": "invalid_request_error"
msg: "param": null,

**Comment by gaboolic** [comment]
谷歌搜一下 调错函数或者传参错了吧
https://www.coder.work/article/8058383

**Comment by DragonBoyYYDS** [comment]
> 谷歌搜一下 调错函数或者传参错了吧 https://www.coder.work/article/8058383
好的，十分感谢。我将继续尝试。
