### ISSUE TITLE
OpenAI API request failed: SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by sansejin1206** [gaboolic/vercel-reverse-proxy#21]
OpenAI API request failed: SSL certificate problem: certificate has expired

请问大佬  我部署成功了 出现了这个问题 是什么原因导致的呢？

**Comment by 8MiYile** [comment]
SSL过期是什么鬼。。。。

**Comment by sansejin1206** [comment]
> SSL 证书问题之证书已过期 什么鬼怎么还有这个提示

确实有这个问题，应该和vercel分配的证书有关

**Comment by 8MiYile** [comment]
@sansejin1206 请尝试刷新在vercel的SSL证书

你可以先尝试我的 我的服务器的地址格式是 https://vercel.rpdl.8mi.work/https://

**Comment by gaboolic** [comment]
我没遇到过，按楼上说的或者重新部署看看可以吗

**Comment by real233** [comment]
> @sansejin1206 请尝试刷新在vercel的SSL证书
> 
> 你可以先尝试我的 我的服务器的地址格式是 https://vercel.rpdl.8mi.work/https://

不用/proxy /httpproxy的方法是什么，我改了几个都变成https:/www.baidu.com 了

**Comment by gaboolic** [comment]
> > @sansejin1206 请尝试刷新在vercel的SSL证书
> > 你可以先尝试我的 我的服务器的地址格式是 https://vercel.rpdl.8mi.work/https://
> 
> 不用/proxy /httpproxy的方法是什么，我改了几个都变成https:/www.baidu.com 了

vercel自己的规则会把//重定向为/，无解

**Comment by real233** [comment]
> > > @sansejin1206 请尝试刷新在vercel的SSL证书
> > > 你可以先尝试我的 我的服务器的地址格式是 https://vercel.rpdl.8mi.work/https://
> > 
> > 
> > 不用/proxy /httpproxy的方法是什么，我改了几个都变成https:/www.baidu.com 了
> 
> vercel自己的规则会把//重定向为/，无解

但是你看他这个地址虽然变成了/ 但是能正常显示页面，你点下面这个，他没加/proxy,怎么做到的？
https://vercel.rpdl.8mi.work/https://www.baidu.com

**Comment by gaboolic** [comment]
> > > > @sansejin1206 请尝试刷新在vercel的SSL证书
> > > > 你可以先尝试我的 我的服务器的地址格式是 https://vercel.rpdl.8mi.work/https://
> > > 
> > > 
> > > 不用/proxy /httpproxy的方法是什么，我改了几个都变成https:/www.baidu.com 了
> > 
> > 
> > vercel自己的规则会把//重定向为/，无解
> 
> 但是你看他这个地址虽然变成了/ 但是能正常显示页面，你点下面这个，他没加/proxy,怎么做到的？ https://vercel.rpdl.8mi.work/https://www.baidu.com


> > > > @sansejin1206 请尝试刷新在vercel的SSL证书
> > > > 你可以先尝试我的 我的服务器的地址格式是 https://vercel.rpdl.8mi.work/https://
> > > 
> > > 
> > > 不用/proxy /httpproxy的方法是什么，我改了几个都变成https:/www.baidu.com 了
> > 
> > 
> > vercel自己的规则会把//重定向为/，无解
> 
> 但是你看他这个地址虽然变成了/ 但是能正常显示页面，你点下面这个，他没加/proxy,怎么做到的？ https://vercel.rpdl.8mi.work/https://www.baidu.com

这个地址vercel会先重定向到https://vercel.rpdl.8mi.work/https:/www.baidu.com
有没有发现这个和我写的一样？我的是中间是proxy， https://vercel.rpdl.8mi.work/proxy/www.baidu.com
只要把proxy改成https:  就好了，但是不完美。原因就是vercel自己的规则会把//重定向为/
