### ISSUE TITLE
Vercel可以突破1000ms的请求时间限制吗【处理请求的时间有限制】

### ISSUE THREAD

**Issue by sansejin1206** [gaboolic/vercel-reverse-proxy#24]
我网上别人说的，我报了这个错误。It appears that your web server has some kind of timeout limit. This can also occur if you are using a VPS, CDN, proxy, firewall, or Cloudflare. To resolve this issue, please contact your hosting provider and request an increase in the timeout limit. Additionally you can enable Custom Prompts for faster response to avoid timeout.
![image](https://github.com/gaboolic/vercel-reverse-proxy/assets/64347551/1606a060-e6ef-4efb-b91e-7ae999f3bc66)

如果您使用 Apache，则需要联系您的托管提供商以查找httpd.conf文件中的当前超时值。该值可以增加。

如果您使用 Nginx，则需要联系您的托管提供商以查找/etc/nginx/conf.d/timeout.conf文件中的当前超时值。

**Comment by gaboolic** [comment]
应该不是1000ms，是10秒，个人账户无解

官方文档：

Serverless Function Execution Timeout
无服务器函数执行超时

The amount of time (in seconds) that a [Serverless Function](https://vercel.com/docs/concepts/functions/serverless-functions) is allowed to process an HTTP request before it must respond. The maximum execution timeout is 10 seconds when deployed on a Personal Account (Hobby plan). For Teams, the execution timeout is 60 seconds (Pro plan) or 900 seconds (Enterprise plan). [Edge Functions](https://vercel.com/docs/concepts/functions/edge-functions) provide an alternative that do not have a [maximum execution timeout](https://vercel.com/docs/concepts/functions/edge-functions/limitations#maximum-initial-response-time) and that also allow you to continue [streaming responses](https://vercel.com/docs/concepts/functions/edge-functions/streaming).
允许无服务器函数在必须响应之前处理 HTTP 请求的时间量（以秒为单位）。部署在个人帐户（爱好计划）上时，最大执行超时为 10 秒。对于 Teams，执行超时为 60 秒（专业计划）或 900 秒（企业计划）。边缘函数提供了一种替代方案，它没有最大执行超时，还允许您继续流式处理响应。

For more information, see the [Execution Timeout](https://vercel.com/docs/concepts/functions/serverless-functions#execution-timeout) section.
有关详细信息，请参阅执行超时部分。
