### ISSUE TITLE
能否在windows或者linux服务器上部署

### ISSUE THREAD

**Issue by Mu-Chen2** [gaboolic/vercel-reverse-proxy#25]
如题，想反代https://sydney.bing.com 最近微软查得严了 cf和vercel的ip全给封了，导致好多第三方项目统统炸裂

**Comment by Nothingness-Void** [comment]
同求

**Comment by gaboolic** [comment]
你如果有自己的服务器 可以用nginx反代。
不过你有自己的服务器都可以搭梯子了吧

**Comment by Nothingness-Void** [comment]
> 你如果有自己的服务器 可以用nginx反代。 不过你有自己的服务器都可以搭梯子了吧

是想搭一个能反代https://sydney.bing.com的公益项目，给别的不能用梯子的人用bing

**Comment by gaboolic** [comment]
> > 你如果有自己的服务器 可以用nginx反代。 不过你有自己的服务器都可以搭梯子了吧
> 
> 是想搭一个能反代https://sydney.bing.com 的公益项目，给别的不能用梯子的人用bing 大佬能讲讲怎么详细操作吗

前提是你的服务器能访问https://sydney.bing.com，然后配置一个proxy_pass就行了
应该就是这样吧
server {
    listen 80;
    server_name 子域名.你的域名.com;

    location /{
       proxy_pass https://sydney.bing.com
    }
}

**Comment by Nothingness-Void** [comment]
> > > 你如果有自己的服务器 可以用nginx反代。 不过你有自己的服务器都可以搭梯子了吧
> > 
> > 
> > 是想搭一个能反代https://sydney.bing.com 的公益项目，给别的不能用梯子的人用bing 大佬能讲讲怎么详细操作吗
> 
> 前提是你的服务器能访问[https://sydney.bing.com，然后配置一个proxy_pass就行了](https://sydney.bing.com%EF%BC%8C%E7%84%B6%E5%90%8E%E9%85%8D%E7%BD%AE%E4%B8%80%E4%B8%AAproxy_pass%E5%B0%B1%E8%A1%8C%E4%BA%86) 应该就是这样吧 server { listen 80; server_name 子域名.你的域名.com;
> 
> ```
> location /{
>    proxy_pass https://sydney.bing.com
> }
> ```
> 
> }

感谢大佬，我去试试

**Comment by Nothingness-Void** [comment]
> proxy_pass https://sydney.bing.com
大佬我服务器那边只用运行nginx就可以吗 不用跑其他的什么服务 我搭完之后访问会提示 502

**Comment by Nothingness-Void** [comment]
大佬我目前用的是这个项目：“https://github.com/adams549659584/go-proxy-bingai”
因为最近微软封cf的ip导致好多人都用不了了，但是我刚好有限制的azure服务器，微软的服务azure的ip肯定能用，所以就想分享出来给别人试试

**Comment by gaboolic** [comment]
> > proxy_pass https://sydney.bing.com
> > 大佬我服务器那边只用运行nginx就可以吗 不用跑其他的什么服务 我搭完之后访问会提示 502

理论上只运行nginx就行…… ~代理caoliu就是这样~

**Comment by Nothingness-Void** [comment]
> > > proxy_pass https://sydney.bing.com
> > > 大佬我服务器那边只用运行nginx就可以吗 不用跑其他的什么服务 我搭完之后访问会提示 502
> 
> 理论上只运行nginx就行…… ~代理caoliu就是这样~

貌似是，不太行。。

**Comment by gaboolic** [comment]
https://www.v2ex.com/t/126028

**Comment by Nothingness-Void** [comment]
> https://www.v2ex.com/t/126028

感谢大佬分享，我看了看代码，我需要的应该是wss能通的
