### ISSUE TITLE
希望代理地址前面可以加http/https

### ISSUE THREAD

**Issue by mingfuyan** [gaboolic/vercel-reverse-proxy#26]
现在是 https://替换为你自己的域名.com/proxy/ **api.openai.com/v1/chat/completions** 替换为https://api.openai.com/v1/chat/completions 。想要 https://替换为你自己的域名.com/proxy/ **https://** api.openai.com/v1/chat/completions。
看了下vercel rewrites的重写文档，还是没搞懂这个正则该怎么写。

**Comment by gaboolic** [comment]
有个朋友改了一下应该可以，https://github.com/gaboolic/vercel-reverse-proxy/pull/23
我还没验证 你可以试试

**Comment by gaboolic** [comment]
貌似有点问题，是vercel的问题，把路径里的//来了一个308跳转，把//变成了/，有点坑啊
例如
https://www.chunqiujinjing.com/proxy//https:/www.chunqiujinjing.com
会先308重定向到https://www.chunqiujinjing.com/proxy/https:/www.chunqiujinjing.com
这是vercel的问题
