### ISSUE TITLE
还是会404

### ISSUE THREAD

**Issue by nosoco** [gaboolic/vercel-reverse-proxy#27]
刚刚Fork过去的，提示如下（vercel的部署状态是Ready）：
404: NOT_FOUND
Code: NOT_FOUND
ID: hnd1::q798b-1691403069095-36b33a769e5a

另外在404的情况下，访问http://{ 替换为你自己的域名.com} /httpproxy/www.google.com/search?q=vercel-reverse-proxy 就和没有挂梯子打开 Google一样，提示网页无法加载

**Comment by gaboolic** [comment]
访问http://{ 替换为你自己的域名.com} /proxy/www.google.com/search?q=vercel-reverse-proxy

**Comment by gaboolic** [comment]
映射规则为/proxy/url映射到https接口，/httpproxy/url映射到http接口
