### ISSUE TITLE
希望能弄的更简单一点

### ISSUE THREAD

**Issue by DevilTear233** [gaboolic/vercel-reverse-proxy#29]
比如http，就https://我的域名/http/需要代理的网址。后面加上/url总是容易记不住，忘打

**Comment by real233** [comment]
同求，我这么写好像不对？
{ "source": "/:url*", "destination": "https://$1" }

**Comment by gaboolic** [comment]
> 比如http，就[https://我的域名/http/需要代理的网址。后面加上/url总是容易记不住，忘打](https://%E6%88%91%E7%9A%84%E5%9F%9F%E5%90%8D/http/%E9%9C%80%E8%A6%81%E4%BB%A3%E7%90%86%E7%9A%84%E7%BD%91%E5%9D%80%E3%80%82%E5%90%8E%E9%9D%A2%E5%8A%A0%E4%B8%8A/url%E6%80%BB%E6%98%AF%E5%AE%B9%E6%98%93%E8%AE%B0%E4%B8%8D%E4%BD%8F%EF%BC%8C%E5%BF%98%E6%89%93)

现在就这样的啊，不用加/url啊
https://替换为你自己的域名.com/proxy/www.google.com/search?q=vercel-reverse-proxy
访问的就是www.google.com/search?q=vercel-reverse-proxy

**Comment by gaboolic** [comment]
> 同求，我这么写好像不对？ { "source": "/:url*", "destination": "https://$1" }

我经过无数次测试，最终最优的配置方法就是像我这个项目这样配。
你那样不能work

**Comment by real233** [comment]
我是想连/proxy/ 或者 /httpproxy 都不加，类似 ghpproxy.com/网址
git clone https://ghproxy.com/https://github.com/stilleshan/ServerStatus

**Comment by real233** [comment]
我搞定了，集百家所长，应该是第一条：

{
  "rewrites": [
    { "source": "/:protocol\\:/:match/:url*", "destination": ":protocol://:match/:url*" },
    { "source": "/:protocol\\:/:match/:url*/", "destination": ":protocol://:match/:url*/" },
    { "source": "/proxy/:match/:url*", "destination": "https://:match/:url*" },
    { "source": "/proxy/:match/:url*/", "destination": "https://:match/:url*/" },
    { "source": "/httpproxy/:match/:url*", "destination": "http://:match/:url*" },
    { "source": "/httpproxy/:match/:url*/", "destination": "http://:match/:url*/" },
    { "source": "/:url(search.*)", "destination": "https://www.google.com/:url" },
    { "source": "/:url(scholar.*)", "destination": "https://scholar.google.com/:url" },
    { "source": "/:match/:url*", "destination": "https://:match/:url*" },
    { "source": "/:match/:url*/", "destination": "https://:match/:url*/" },
    { "source": "/h/:match/:url*", "destination": "http://:match/:url*" },
    { "source": "/h/:match/:url*/", "destination": "http://:match/:url*/" },
    { "source": "/:match/:url(google.com)", "destination": "https://www.google.com/" },
    { "source": "/:url(search.*)", "destination": "https://www.google.com/:url" },
    { "source": "/:url(scholar.*)", "destination": "https://scholar.google.com/:url" },
    { "source": "/wss/:match/:url*", "destination": "wss://:match/:url*" },
    { "source": "/:protocol/:match/:url*", "destination": ":protocol://:match/:url*" },
    { "source": "/:protocol/:match/:url*/", "destination": ":protocol://:match/:url*/" },
    { "source": "/:protocol*/:match/:url*", "destination": ":protocol://:match/:url*" },
    { "source": "/:protocol*/:match/:url*/", "destination": ":protocol://:match/:url*/" }

  ]
}

**Comment by gaboolic** [comment]
> 我是想连/proxy/ 或者 /httpproxy 都不加，类似 ghpproxy.com/网址 git clone https://ghproxy.com/https://github.com/stilleshan/ServerStatus

可以用https://github.com/gaboolic/cloudflare-reverse-proxy这个项目做到

**Comment by gaboolic** [comment]
> 我搞定了，集百家所长，应该是第一条：
> 
> { "rewrites": [ { "source": "/:protocol\:/:match/:url*", "destination": ":protocol://:match/:url*" }, { "source": "/:protocol\:/:match/:url*/", "destination": ":protocol://:match/:url*/" }, { "source": "/proxy/:match/:url*", "destination": "https://:match/:url*" }, { "source": "/proxy/:match/:url*/", "destination": "https://:match/:url*/" }, { "source": "/httpproxy/:match/:url*", "destination": "http://:match/:url*" }, { "source": "/httpproxy/:match/:url*/", "destination": "http://:match/:url*/" }, { "source": "/:url(search._)", "destination": "https://www.google.com/:url" }, { "source": "/:url(scholar._)", "destination": "https://scholar.google.com/:url" }, { "source": "/:match/:url*", "destination": "https://:match/:url*" }, { "source": "/:match/:url*/", "destination": "https://:match/:url*/" }, { "source": "/h/:match/:url*", "destination": "http://:match/:url*" }, { "source": "/h/:match/:url*/", "destination": "http://:match/:url*/" }, { "source": "/:match/:url(google.com)", "destination": "https://www.google.com/" }, { "source": "/:url(search._)", "destination": "https://www.google.com/:url" }, { "source": "/:url(scholar._)", "destination": "https://scholar.google.com/:url" }, { "source": "/wss/:match/:url*", "destination": "wss://:match/:url*" }, { "source": "/:protocol/:match/:url*", "destination": ":protocol://:match/:url*" }, { "source": "/:protocol/:match/:url*/", "destination": ":protocol://:match/:url*/" }, { "source": "/:protocol*/:match/:url*", "destination": ":protocol://:match/:url*" }, { "source": "/:protocol*/:match/:url*/", "destination": ":protocol://:match/:url*/" }
> 
> ] }

第一条其实是vercel先把两个/变成一个/，不完美

**Comment by gaboolic** [comment]
多一次重定向
