### ISSUE TITLE
希望地址上能用直接加vecel 反代url 前缀的格式，https://替换为你自己的域名.com/https://objects.githubusercontent.com/github-production-release-asset-2e65be/xxxxxx 

### ISSUE THREAD

**Issue by fscarmen** [gaboolic/vercel-reverse-proxy#30]
感谢大佬的项目。同时我想同类项目均在原地址前面直接加上反代cdn地址，连 https:// 这里也保留，希望本项目也添加这样的方式。

https://objects.githubusercontent.com/github-production-release-asset-2e65be/xxxxxx
改为
https://替换为你自己的域名.com/https://objects.githubusercontent.com/github-production-release-asset-2e65be/xxxxxx
或者
https://替换为你自己的域名.com/proxy/https://objects.githubusercontent.com/github-production-release-asset-2e65be/xxxxxx

**Comment by gaboolic** [comment]
f佬，可以用https://github.com/gaboolic/cloudflare-reverse-proxy  这个项目
vercel我发现它有个问题是会把//自动再重定向成/，所以没办法了

**Comment by fscarmen** [comment]
你好呀，我发现有个问题，vercel 能找代 api.github，但worker不行，我用你的两个项目，以下为截图，从第一个截图下载 github 上的 release 来看是已经搭建成功了的，但第二个截图可以看到 worker 版本的不能反代 api.github

截图一：
<img width="1245" alt="image" src="https://github.com/gaboolic/vercel-reverse-proxy/assets/62703343/e1ced3bd-b9d6-4be5-bc90-497ab9cbc2f1">

截图二：
<img width="1081" alt="image" src="https://github.com/gaboolic/vercel-reverse-proxy/assets/62703343/8c19e2d1-bc9f-4754-8468-52b8e947df9a">

**Comment by gaboolic** [comment]
> 

worker版本的 /proxy/ 后面跟的就是原始完整Url，带https的
我看你第二个图proxy/后面没有带https://

**Comment by fscarmen** [comment]
是的，我看了说明，是与vercel不同的，我也加上了 https://，仍然是不行的，你用你的 worker 看看呢，谢谢！
```
wget -qO- -T1 -t1 "https://api.github.com/repos/octeep/wireproxy/releases/latest" | grep "tag_name"
```

<img width="1275" alt="image" src="https://github.com/gaboolic/vercel-reverse-proxy/assets/62703343/e1adcb62-328a-4c29-adc6-b3672ae95d0c">

**Comment by gaboolic** [comment]
之前合并了pr 有点问题
