### ISSUE TITLE
跳转问题

### ISSUE THREAD

**Issue by Hakuin123** [gaboolic/vercel-reverse-proxy#32]
emm不知道怎么描述，举个例子吧：

访问`https://自定义域名/proxy/www.google.com`，点击页面上的搜索按钮后会跳转到`https://自定义域名/search?q=xxxx`，而不是`https://自定义域名/proxy/www.google.com/search?q=xxxx`，然后毫无悬念地404

**Comment by gaboolic** [comment]
这种需求……直接科学吧
