### ISSUE TITLE
可以用于chat.openai.com页面代理吗

### ISSUE THREAD

**Issue by cncbec** [gaboolic/vercel-reverse-proxy#4]
应该是被cloudflare保护了

**Comment by gaboolic** [comment]
这个不行。但是一些其他的软件、浏览器插件以及调接口是没问题的
例如OpenAI Translator插件，可以设置API URL、API URL Path
python代码里面，可以设置openai.api_base

**Comment by gaboolic** [comment]
不过我想到 如果写一个浏览器插件，然后把所有的请求url前面加上 域名/proxy，应该就可以了

**Comment by gaboolic** [comment]
> 不过我想到 如果写一个浏览器插件，然后把所有的请求url前面加上 域名/proxy，应该就可以了

然后再加点加密算法，我靠，这不就是……

**Comment by cncbec** [comment]
浏览器插件走vercel？
