### ISSUE TITLE
请教如何利用这个隐藏端口号？

### ISSUE THREAD

**Issue by woshichenghaibo** [gaboolic/vercel-reverse-proxy#41]
我有一个域名用的vercel的CDN，
比如http://a.b.com:5000访问。

我如何加上SSL然后去掉端口号变成https://a.b.com

谢谢。

**Comment by gaboolic** [comment]
我记得vercel的CDN 没端口号？

**Comment by gaboolic** [comment]
这个项目解决不了此问题  感觉你需要的是nginx那样的

**Comment by woshichenghaibo** [comment]
查了一下，发现vercel不支持端口重写
________________________________
发件人: gaboolic ***@***.***>
发送时间: 2024年4月12日 15:56
收件人: gaboolic/vercel-reverse-proxy ***@***.***>
抄送: woshichenghaibo ***@***.***>; Author ***@***.***>
主题: Re: [gaboolic/vercel-reverse-proxy] 请教如何利用这个隐藏端口号？ (Issue #41)


这个项目解决不了此问题 感觉你需要的是nginx那样的

―
