### ISSUE TITLE
谷歌Gemini的接口怎么代理？好像无法处理

### ISSUE THREAD

**Issue by admlke** [gaboolic/vercel-reverse-proxy#43]
谷歌请求地址例如： https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=$API_KEY，使用代理域名/proxy/generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=$API_KEY,此时访问不成功，该如何修改？

**Comment by chunzha1** [comment]
我也有同样的问题，代理了gemini，然后国内ip访问会报 User location is not supported for the API use.

**Comment by gaboolic** [comment]
> 我也有同样的问题，代理了gemini，然后国内ip访问会报 User location is not supported for the API use.

那可能不行 它限制了
